### ISSUE TITLE
Editing plugin details removes the 'replaces' key from plugin.yaml

### ISSUE THREAD

**Issue by ericp-mrel** [wintercms/wn-builder-plugin#10]
If I have the following plugin.yaml file:

```yaml
# plugin.yaml

plugin:
    name: 'acme.blog::lang.plugin.name'
    description: 'Plugin Description'
    author: 'Author Name'
    icon: wn-icon-chain
    homepage: 'https://example.com'
    replaces:
        Acme.Blog: '<3.0.0'
```
And I edit the plugin details by clicking on the plugin gear icon and save the changes, the replaces definition is removed from the yaml and results in the following:

```yaml
# plugin.yaml

plugin:
    name: 'acme.blog::lang.plugin.name'
    description: 'Plugin Description'
    author: 'Author Name'
    icon: wn-icon-chain
    homepage: 'https://example.com'
```

**Comment by arvislacis** [comment]
I think this is because Builder plugin allows you to only edit `name`,  `description`,  `author`,  `icon` and `homepage` fields when you open plugin configuration pop-up (click on gear icon). And only these fields are then saved back to YAML configuration file after save.

I personally don't see this as a big issue because you probably added `replaces` section externally.

One possible solution may be to add `replaces` repeater or datatable field into configuration pop-up and logics so it gets properly loaded and saved.

**Comment by arvislacis** [comment]
@ericp-mrel May I also ask where did you find out that you can use `replaces` in `plugin.yaml` configuration? As far as I quickly searched then you can use it under `pluginDetails()` function - https://wintercms.com/docs/plugin/registration#plugin-replace - but I am not sure about `plugin.yaml`. Does it even work when used from YAML file?

**Comment by ericp-mrel** [comment]
@arvislacis If you look at the PluginBase.php class, you can see the base `pluginDetails()` method will parse the data from the plugin.yaml file if it exists and returns the data under the `plugin:` key as an array. See https://github.com/wintercms/winter/blob/develop/modules/system/classes/PluginBase.php#L57-L73

Otherwise, if you don't have/use the plugin.yaml file you would override the `pluginDetails()` method in your Plugin's Plugin.php file and define the array there.

And yes, the replaces key does work in the YAML file, I now have two plugins defining the replaces in the plugin.yaml file and is working just fine. After all, the yaml file just gets parsed into a PHP array anyways.

Hope this makes sense!

**Comment by LukeTowers** [comment]
@arvislacis give #10 a test please

**Comment by arvislacis** [comment]
@ericp-mrel Give a try to https://github.com/wintercms/wn-builder-plugin/issues/10

**Comment by bennothommo** [comment]
@LukeTowers @arvislacis don't you guys mean #11? 😛

**Comment by LukeTowers** [comment]
Whoops!

**Comment by ericp-mrel** [comment]
@LukeTowers It's working for me, even tested it with multiple replaces items

Example of what I've tested.
```yaml
replaces:
  Acme.Plugin: '<1.0.0'
  Winter.Plugin: <5.5.5
```
